#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

exec git update-server-info

# My Stuff
# web repository directory
REPO_DIR="${git rev-parse --show-toplevel}"

echo
echo "---"
echo "--- Resetting ownership to ${OWNER} on ${REPO_DIR}"

sudo chmod -Rfv a+rwx $REPO_DIR

echo "--- Done"
echo "---"
