#!/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

exec git update-server-info

# My Stuff
# Repository directory
REPO_DIR=$(git rev-parse --show-toplevel)
echo "---"
echo "--- setting ownership to u=rwx,g=rwx,o=r on ${REPO_DIR}"

find $REPO_DIR -perm /u=rwx,g=rwx,o=r -exec chmod -R u=rwx,g=rwx,o=r {} +

echo "--- Done"
echo "---"