#!/bin/bash

# web repository directory
REPO_DIR=$(git rev-parse --show-toplevel)

echo
echo "---"
echo "--- setting ownership to a+rwx on ${REPO_DIR}"

chmod -R a+rwx $REPO_DIR

echo "--- Done"
echo "---"
