#!/bin/bash

# web repository directory
REPO_DIR=$(git rev-parse --show-toplevel)

echo
echo "---"
echo "--- Resetting ownership to ${OWNER} on ${REPO_DIR}"

chmod -Rfv a+rwx $REPO_DIR

echo "--- Done"
echo "---"
