#!/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

exec git update-server-info

# My Stuff
# web repository directory
REPO_DIR=$(git rev-parse --show-toplevel)

echo
echo "---"
echo "--- setting ownership to a+rwx on ${REPO_DIR}"

chmod -R a+rwx $REPO_DIR

echo "--- Done"
echo "---"
